// 子どもアイコン絵文字マッピング
export const childEmojiMap: {[key: string]: string} = {
  'user': '👤',
  'smile': '😊',
  'heart': '❤️',
  'star': '⭐',
  'sun': '☀️',
  'moon': '🌙',
  'cloud': '☁️',
  'flower': '🌸',
  'tree': '🌳',
  'cat': '🐱',
  'dog': '🐶',
  'rabbit': '🐰',
  'bear': '🐻',
  'panda': '🐼',
  'monkey': '🐵',
  'penguin': '🐧',
  'bird': '🐦',
  'fish': '🐠',
  'turtle': '🐢',
  'butterfly': '🦋',
  'bee': '🐝',
  'ladybug': '🐞',
  'rocket': '🚀',
  'award': '🏆',
  'gift': '🎁',
  // 追加アイコン
  'lion': '🦁',
  'tiger': '🐯',
  'elephant': '🐘',
  'giraffe': '🦒',
  'zebra': '🦓',
  'unicorn': '🦄',
  'dragon': '🐉',
  'dolphin': '🐬',
  'whale': '🐳',
  'octopus': '🐙',
  'shark': '🦈',
  'frog': '🐸',
  'fox': '🦊',
  'wolf': '🐺',
  'koala': '🐨',
  'hedgehog': '🦔',
  'owl': '🦉',
  'chicken': '🐔',
  'duck': '🦆',
  'swan': '🦢',
  'eagle': '🦅',
  'peacock': '🦚',
  'parrot': '🦜',
  'flamingo': '🦩',
  'snail': '🐌',
  'ant': '🐜',
  'spider': '🕷️',
  'candy': '🍬',
  'icecream': '🍦',
  'cake': '🍰',
  'pizza': '🍕',
  'hamburger': '🍔',
  'taco': '🌮',
  'sushi': '🍣',
  'apple': '🍎',
  'banana': '🍌',
  'grapes': '🍇',
  'strawberry': '🍓',
  'watermelon': '🍉',
  'cherry': '🍒',
  'peach': '🍑',
  'mango': '🥭',
  'balloon': '🎈',
  'crown': '👑',
  'robot': '🤖',
  'alien': '👽',
  'ghost': '👻',
  'ninja': '🥷',
  'superhero': '🦸',
  'fairy': '🧚',
  'mermaid': '🧜',
  'wizard': '🧙',
  'rainbow': '🌈',
  'meteor': '☄️',
  'lightning': '⚡',
  'fire': '🔥',
  'snowflake': '❄️',
  'beach': '🏖️',
  'mountain': '🏔️',
  'football': '⚽',
  'basketball': '🏀',
  'baseball': '⚾',
  'tennis': '🎾',
  'gaming': '🎮',
  'medal': '🏅',
  'trophy': '🏆',
  'car': '🚗',
  'train': '🚂',
  'airplane': '✈️',
  'ship': '🚢',
  'guitar': '🎸',
  'piano': '🎹',
  'trumpet': '🎺',
  'drum': '🥁',
  'microphone': '🎤',
  'magicwand': '🪄',
  'book': '📚',
  'pencil': '✏️',
  'palette': '🎨',
  'camera': '📷',
  'lightbulb': '💡',
  'hat': '🎩',
  'crystal': '🔮',
  'lock': '🔒',
  'key': '🔑',
  'compass': '🧭',
  'clock': '⏰',
  'heart_purple': '💜',
  'heart_blue': '💙',
  'heart_green': '💚',
  'heart_yellow': '💛',
  'heart_pink': '💖',
};

// お手伝い絵文字マッピング
export const choreEmojiMap: {[key: string]: string} = {
  'trash': '🗑️',
  'book': '📚',
  'broom': '🧹',
  'dish': '🍽️',
  'laundry': '👕',
  'plant': '🌱',
  'bed': '🛏️',
  'pet': '🐶',
  'toy': '🧸',
  'clean': '🧼',
  'mail': '📬',
  'shop': '🛒',
  'star': '⭐',
  'check': '✅',
  'shirt': '👕',
  'box': '📦',
  // 追加アイコン
  'water': '💧',
  'bath': '🛁',
  'kitchen': '🍳',
  'vacuum': '🧹',
  'window': '🪟',
  'wipe': '🧽',
  'shoes': '👟',
  'fold': '👚',
  'iron': '🔥',
  'wash': '🧴',
  'rinse': '🚿',
  'cook': '👨‍🍳',
  'table': '🪑',
  'floor': '🧵',
  'dust': '✨',
  'doorknob': '🚪',
  'mirror': '🪞',
  'sink': '🚰',
  'fridge': '🧊',
  'microwave': '🔄',
  'sweep': '🧹',
  'mop': '🧴',
  'garden': '🌿',
  'flowers': '🌷',
  'leaves': '🍂',
  'rake': '🌿',
  'groceries': '🛍️',
  'fruits': '🍎',
  'vegetables': '🥦',
  'meat': '🥩',
  'eggs': '🥚',
  'bread': '🍞',
  'rice': '🍚',
  'soup': '🍲',
  'salad': '🥗',
  'juice': '🧃',
  'milk': '🥛',
  'cookies': '🍪',
  'cake': '🎂',
  'trash_bin': '🗑️',
  'recycle': '♻️',
  'sort': '📑',
  'eraser': '🧽',
  'homework': '📝',
  'backpack': '🎒',
  'notebook': '📔',
  'calculator': '🧮',
  'computer': '💻',
  'tablet': '📱',
  'paintbrush': '🖌️',
  'guitar': '🎸',
  'flute': '🎵',
  'sports': '⚽',
  'medicine': '💊',
  'bandage': '🩹',
  'toothbrush': '🪥',
  'keys': '🔑',
  'bicycle': '🚲',
  'bus': '🚌',
  'call': '📞',
  'message': '💬',
  'email': '📧',
  'calendar': '📅',
  'battery': '🔋',
  'bulb': '💡',
};

// アイコン選択オプション
export const iconOptions = [
  { value: 'bed', label: 'ベッド', emoji: '🛏️' },
  { value: 'dish', label: 'おさら', emoji: '🍽️' },
  { value: 'broom', label: 'ほうき', emoji: '🧹' },
  { value: 'trash', label: 'ごみ', emoji: '🗑️' },
  { value: 'shirt', label: 'ふく', emoji: '👕' },
  { value: 'box', label: 'はこ', emoji: '📦' },
  { value: 'star', label: 'ほし', emoji: '⭐' },
  { value: 'book', label: 'ほん', emoji: '📚' },
  { value: 'clean', label: 'そうじ', emoji: '🧼' },
  { value: 'wash', label: 'せんたく', emoji: '🧴' },
  { value: 'fold', label: 'たたむ', emoji: '👚' },
  { value: 'bath', label: 'おふろ', emoji: '🛁' },
  { value: 'wipe', label: 'ふく', emoji: '🧽' },
  { value: 'kitchen', label: 'りょうり', emoji: '🍳' },
  { value: 'water', label: 'みず', emoji: '💧' },
  { value: 'plant', label: 'しょくぶつ', emoji: '🌱' },
  { value: 'pet', label: 'ペット', emoji: '🐶' },
  { value: 'cook', label: 'クッキング', emoji: '👨‍🍳' },
  { value: 'garden', label: 'にわしごと', emoji: '🌿' },
  { value: 'flowers', label: 'はな', emoji: '🌷' },
  { value: 'groceries', label: 'かいもの', emoji: '🛍️' },
  { value: 'recycle', label: 'リサイクル', emoji: '♻️' },
  { value: 'homework', label: 'しゅくだい', emoji: '📝' },
  { value: 'sort', label: 'ぶんべつ', emoji: '📑' },
  { value: 'computer', label: 'パソコン', emoji: '💻' },
  { value: 'tablet', label: 'タブレット', emoji: '📱' },
  { value: 'toothbrush', label: 'はみがき', emoji: '🪥' },
  { value: 'toilet', label: 'トイレ', emoji: '🚽' },
  { value: 'window', label: 'まど', emoji: '🪟' },
  { value: 'mirror', label: 'かがみ', emoji: '🪞' },
  { value: 'laundry', label: 'せんたくもの', emoji: '👕' },
  { value: 'mail', label: 'ゆうびん', emoji: '📬' },
  { value: 'shop', label: 'おみせ', emoji: '🛒' },
  { value: 'check', label: 'チェック', emoji: '✅' },
  { value: 'toy', label: 'おもちゃ', emoji: '🧸' },
];

// アバターオプション
export const avatarOptions = [
  { value: 'smile', label: 'えがお', emoji: '😊' },
  { value: 'heart', label: 'ハート', emoji: '❤️' },
  { value: 'user', label: 'ひと', emoji: '👤' },
  { value: 'award', label: 'メダル', emoji: '🏆' },
  { value: 'gift', label: 'プレゼント', emoji: '🎁' },
  { value: 'cat', label: 'ねこ', emoji: '🐱' },
  { value: 'dog', label: 'いぬ', emoji: '🐶' },
  { value: 'rabbit', label: 'うさぎ', emoji: '🐰' },
  { value: 'bear', label: 'くま', emoji: '🐻' },
  { value: 'panda', label: 'パンダ', emoji: '🐼' },
  { value: 'monkey', label: 'さる', emoji: '🐵' },
  { value: 'penguin', label: 'ペンギン', emoji: '🐧' },
  { value: 'bird', label: 'とり', emoji: '🐦' },
  { value: 'fish', label: 'さかな', emoji: '🐠' },
  { value: 'turtle', label: 'かめ', emoji: '🐢' },
  { value: 'butterfly', label: 'ちょう', emoji: '🦋' },
  { value: 'bee', label: 'はち', emoji: '🐝' },
  { value: 'lion', label: 'ライオン', emoji: '🦁' },
  { value: 'fox', label: 'きつね', emoji: '🦊' },
  { value: 'unicorn', label: 'ユニコーン', emoji: '🦄' },
  { value: 'dragon', label: 'ドラゴン', emoji: '🐉' },
  { value: 'robot', label: 'ロボット', emoji: '🤖' },
  { value: 'alien', label: 'エイリアン', emoji: '👽' },
  { value: 'ghost', label: 'おばけ', emoji: '👻' },
  { value: 'ninja', label: 'にんじゃ', emoji: '🥷' },
  { value: 'superhero', label: 'ヒーロー', emoji: '🦸' },
  { value: 'wizard', label: 'まほうつかい', emoji: '🧙' },
  { value: 'fairy', label: 'ようせい', emoji: '🧚' },
  { value: 'mermaid', label: 'にんぎょ', emoji: '🧜' },
  { value: 'crown', label: 'おうかん', emoji: '👑' },
  { value: 'rainbow', label: 'にじ', emoji: '🌈' },
  { value: 'sun', label: 'たいよう', emoji: '☀️' },
  { value: 'moon', label: 'つき', emoji: '🌙' },
  { value: 'star', label: 'ほし', emoji: '⭐' },
  { value: 'snowflake', label: 'ゆき', emoji: '❄️' },
  { value: 'fire', label: 'ひ', emoji: '🔥' },
  { value: 'lightning', label: 'かみなり', emoji: '⚡' },
  { value: 'rocket', label: 'ロケット', emoji: '🚀' },
  { value: 'car', label: 'くるま', emoji: '🚗' },
  { value: 'airplane', label: 'ひこうき', emoji: '✈️' },
  { value: 'football', label: 'サッカー', emoji: '⚽' },
  { value: 'basketball', label: 'バスケ', emoji: '🏀' },
  { value: 'baseball', label: 'やきゅう', emoji: '⚾' },
  { value: 'gaming', label: 'ゲーム', emoji: '🎮' },
  { value: 'guitar', label: 'ギター', emoji: '🎸' },
  { value: 'microphone', label: 'マイク', emoji: '🎤' },
  { value: 'cake', label: 'ケーキ', emoji: '🍰' },
  { value: 'pizza', label: 'ピザ', emoji: '🍕' },
  { value: 'icecream', label: 'アイス', emoji: '🍦' },
  { value: 'candy', label: 'アメ', emoji: '🍬' },
  { value: 'heart_purple', label: 'むらさきハート', emoji: '💜' },
  { value: 'heart_blue', label: 'あおハート', emoji: '💙' },
  { value: 'heart_green', label: 'みどりハート', emoji: '💚' },
  { value: 'heart_yellow', label: 'きいろハート', emoji: '💛' },
  { value: 'heart_pink', label: 'ピンクハート', emoji: '💖' },
];

// カラーオプション
export const colorOptions = [
  { value: '#4dabf7', label: 'あお' },
  { value: '#ff922b', label: 'オレンジ' },
  { value: '#51cf66', label: 'みどり' },
  { value: '#ffd43b', label: 'きいろ' },
  { value: '#ff6b6b', label: 'あか' },
  { value: '#cc5de8', label: 'むらさき' },
  { value: '#f06595', label: 'ピンク' },
  { value: '#22b8cf', label: 'みずいろ' },
  { value: '#fab005', label: 'ゴールド' },
  { value: '#20c997', label: 'ミント' },
  { value: '#7950f2', label: 'しょうぶいろ' },
  { value: '#868e96', label: 'グレー' },
]; 